<?php

namespace Nip\Http\Tests;

use Nip\Container\Container;
use PHPUnit\Framework\TestCase;

/**
 * Class AbstractTest
 */
abstract class AbstractTest extends TestCase
{
    protected $object;

    /**
     * @var \UnitTester
     */
    protected $tester;

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        Container::setInstance(null);
    }
}
